spring:
  #  profiles:
  #    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/neighbor
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #        QueryDSL로 사용된 JPQL 보기
        use_sql_comments: true
        default_batch_fetch_size: 500 # 컬렉션 조회 페이징 및 최적화

logging.level:
  org.hibernate.SQL: debug